name: GitHub Actions To Move Folder

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Move Folder
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Environment
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "当前工作目录: $(pwd)"
          ls -la $GITHUB_WORKSPACE

      - name: Execute Move Script
        run: |
          git clone -b cherry/master https://github.com/yu13140/kernel_cherry_sdm439.git
          git clone -b olive-q-oss https://github.com/yu13140/Xiaomi_Kernel_OpenSource.git
          cp -r ${{ GITHUB_WORKSPACE }}/kernel_cherry_sdm439/drivers/net/wireless/* ${{ GITHUB_WORKSPACE }}/Xiaomi_Kernel_OpenSource/drivers/net/wireless/
          cd ${{ GITHUB_WORKSPACE }}/Xiaomi_Kernel_OpenSource
          git add .
          git commit -m "try move"
          git push -u origin olive-q-oss